language: node_js
node_js:
  - 9
cache:
  directories:
    - node_modules
before_script:
  - cd frontend/
install:
  - npm install
  - npm install -g @vue/cli-service
script:
  - npm run test:unit
on:
  branch: ci/paula