language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
script:
  - npm install -g @vue/cli
  - npm install
  - npm run test:unit
on:
  branch: main
notifications:
  slack: sytw-07gamingit:hevaRMSoko92Uf6uDRVLzQ6o
