language: node_js
node_js:
  - 9
cache:
  directories:
    - node_modules
before_script:
  - cd frontend/
  - npm install
# install:
#   - npm install -g @vue/cli-service
#   - @vue/cli-plugin-unit-jest
script:
  - npm run test:unit
on:
  branch: ci/paula