language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
script:
  - npm install -g @vue/cli
  - npm install 
  - npm run test:unit
  - npm install -D codecov
  - npm run test:coverage
  # - bash <(curl -s https://codecov.io/bash) -v -t 6f5987bd-0f38-4561-97a1-5c6a71e60f73
after-success:
  - ./node_modules/.bin/codecov --token="6f5987bd-0f38-4561-97a1-5c6a71e60f73"
on:
  branch: main
notifications:
  slack: 
    rooms:
      - sytw-07gamingit:hevaRMSoko92Uf6uDRVLzQ6o#travis-ci
      - sytwull:9RHWkAunQmp2IhenSjqSWWK4#e07
