language: node_js
node_js:
  - 9
cache:
  directories:
    - node_modules
before_install:
  - cd frontend/
install:
  - npm install -g @vue/cli
  - npm install
  # - npm install -g @vue/cli-service
  # - @vue/cli-plugin-unit-jest
script:
  - pwd
  - npm run test:unit
on:
  branch: ci/paula