language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
script:
  - npm install -g @vue/cli
  - npm install 
  - npm run test:unit
  - bash <(curl -s https://codecov.io/bash) -v -t 6f5987bd-0f38-4561-97a1-5c6a71e60f73
on:
  branch: ci/miriam
notifications:
  slack: 
    rooms:
      - sytw-07gamingit:hevaRMSoko92Uf6uDRVLzQ6o#travis-ci
      - sytwull:9RHWkAunQmp2IhenSjqSWWK4#e07
